# Generated by Django 6.0.6 on 2026-06-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='foto',
            new_name='miniatura',
        ),
    ]
